cmd/main.go, cmd/validate.go
=> Removing unused code

cmd/ingress.go, cmd/ingress_to_pod.go, cmd/main.go, pkg/connectivity/pod-to-pod.go, pkg/ingress/pod.go, pkg/ingress/types.go, tests/ingress-to-pod.sh
First steps towards checking whether Ingress is configured correctly.
=> Adding the beginnings of Ingress checks

pkg/kuberneteshelper/pod.go
This PR adds `GetKubeClient()` - a common way to get a Kubernetes clientset.
=> Introducing GetKubeClient()

cmd/connectivity.go, cmd/connectivity_pod_to_pod.go, cmd/main.go
=> Remove unused code

cmd/connectivity_pod_to_pod.go, cmd/ingress_to_pod.go, pkg/connectivity/pod-to-pod.go, pkg/kuberneteshelper/pod.go
This PR is stacked on https://github.com/openservicemesh/osm-health/pull/11
=> Use the new GetKubeClient()

go.mod, go.sum, pkg/envoy/config.go, pkg/envoy/lds.go, pkg/envoy/parse.go, pkg/envoy/parse_test.go, pkg/envoy/types.go, tests/sample-enovy-config-dump.json
This PR creates an empty `GetEnvoyConfig()`, and a new `ParseEnvoyConfig()`
---
This PR will leverage the facility fetching Envoy configs from https://github.com/openservicemesh/osm-health/pull/14
=> Parse Enovy ConfigDump

go.mod, pkg/connectivity/pod-to-pod.go, pkg/envoy/config.go, pkg/envoy/errors.go, pkg/envoy/lds.go, pkg/envoy/lds_test.go, pkg/envoy/parse_test.go, pkg/envoy/types.go, pkg/osm/listener_names_per_osm_version.go
This PR adds a very basic check for Envoy listener -- answers the question - does "outbound-listener" exist.
=> Check for correct configuration of Envoy listener for a given Pod

pkg/kuberneteshelper/types.go
This PR renames some of the loggers in osm-health.
=> Fix loggers

pkg/kubernetes/pod/containers.go
Updates pod checks to match changes in #22 
=> chore(checks): update pod checks for interface compliance

pkg/kubernetes/pod/containers_test.go
=> test(containers): add test for num containers check

pkg/kubernetes/pod/labels_test.go
=> test(pod/labels): pod has valid proxy uuid label

pkg/common/types.go, pkg/connectivity/pod-to-pod.go
This PR removes unused structs.
=> Remove unused structs

pkg/common/printer.go
=> fmt(printer): print check results as a table

cmd/control_plane.go, cmd/control_plane_status.go, cmd/main.go, pkg/osm/status.go, pkg/osm/types.go, pkg/osm/types_test.go
Add wireframe for osm control plane checks
=> Add wireframe for osm control plane checks

pkg/kubernetes/pod/containers.go, pkg/kubernetes/pod/labels.go
=> checks(pod): add suggestions for pod checks

pkg/kubernetes/podhelper/events.go
Command without a default ns set was failing
=> fix(events): add namespace flag to suggested command

cmd/connectivity_pod_to_pod.go, pkg/common/types.go, pkg/connectivity/pod-to-pod.go, pkg/kubernetes/podhelper/containers.go, pkg/kubernetes/podhelper/containers_test.go, pkg/kubernetes/podhelper/errors.go, pkg/kuberneteshelper/pod.go
Also reduces min containers check to only check for 2 containers (app and envoy)
=> check(containers): add check for osm init container image

go.mod, pkg/connectivity/pod-to-pod.go, pkg/kuberneteshelper/pod.go, pkg/smi/errors.go, pkg/smi/traffic_split.go
=> check(smi): add check for dest pod in traffic split

pkg/connectivity/pod-to-pod.go
Rearranges checks so each check is called on fromPod, then toPod. Earlier this was the case for half the checks but some of the initial checks were grouped by pod instead.
=> chore(connectivity): rearrange checks to group by check instead of pod

pkg/envoy/cds.go, pkg/kuberneteshelper/pod.go
Updates the GetMatchingServices return type to be reusable
=> ref(cds): replace local function to reuse helper

pkg/connectivity/pod-to-pod.go, pkg/connectivity/pod-to-url.go, pkg/envoy/cds.go, pkg/envoy/cds_test.go, pkg/envoy/eds.go, pkg/envoy/eds_test.go, pkg/envoy/envoy_container_logs.go, pkg/envoy/lds.go, pkg/envoy/lds_test.go, pkg/envoy/rds.go, pkg/envoy/rds_test.go, pkg/ingress/pod.go, pkg/kubernetes/namespace/injected.go, pkg/kubernetes/namespace/monitored.go, pkg/kubernetes/podhelper/containers.go, pkg/kubernetes/podhelper/containers_test.go, pkg/kubernetes/podhelper/events.go, pkg/kubernetes/podhelper/labels.go, pkg/kubernetes/podhelper/labels_test.go, pkg/smi/traffic_split.go, pkg/smi/traffic_split_test.go
ref: https://github.com/openservicemesh/osm-health/pull/74#discussion_r697554603
=> chore(*): rename checks to follow GoLang New() convention

pkg/connectivity/pod-to-pod.go
=> chore(connectivity): rename pods to match names in each check

pkg/common/outcomes/diagnostic_outcome.go, pkg/common/outcomes/failed_outcome.go, pkg/common/outcomes/successful_outcome.go, pkg/common/outcomes/unknown_outcome.go
Removes unicode characters since they don't appear on most consoles
=> Remove unicode characters

pkg/connectivity/pod-to-pod.go, pkg/kubernetes/podhelper/container_logs.go, pkg/kubernetes/podhelper/container_logs_test.go, pkg/kubernetes/podhelper/containers.go, pkg/kubernetes/podhelper/containers_test.go, pkg/kubernetes/podhelper/errors.go, pkg/osm/osminit.go
Check for bad logs in osm-init container…or pod log checks.
Also adds UTs for various pod log and pod container checks.
=> feat(containers): Check for bad logs in osm-init container

pkg/connectivity/pod-to-pod.go, pkg/connectivity/pod-to-url.go, pkg/envoy/parse.go, pkg/kuberneteshelper/pod.go, pkg/osm/status.go
This PR fixes log.Error messages where these are not setup correctly
=> Correct error log messages

pkg/connectivity/pod-to-pod.go, pkg/envoy/rds.go, pkg/envoy/rds_test.go
Check pod service names when performing rds route domain checks.
Currently, the pre-existing rds route domain checks only check for
the existence of the pod name in RDS routes. The pre-existing
check's logic is incorrect and this causes the RDS checks to
always fail.
The correct way to check for RDS routes is to check pod service
names, not pod names.
=> fix(envoy): Use pod service names for rds checks

cmd/connectivity_pod_to_url.go, pkg/connectivity/pod-to-url.go, pkg/osm/utils.go
=> feat(osm): dynamically get osm version for pod-to-url check

pkg/connectivity/pod-to-pod.go, pkg/osm/smi.go, pkg/smi/split/traffic_split.go, pkg/smi/split/traffic_split_test.go
Change for consistency with other smi checks + framework for future versioning of smi trafficsplit
=> ref(trafficsplit): add smi versioning mechanism for trafficsplit

.github/workflows/main.yml, README.md
Docs will need further updating once we cut a release
=> docs(*): document usage of osm-health

pkg/connectivity/pod-to-pod.go, pkg/envoy/errors.go, pkg/envoy/lds.go, pkg/envoy/lds_test.go, pkg/osm/types_test.go, pkg/smi/errors.go
Signed-off-by: jaellio <jaellio@microsoft.com>
=> feat(lds): check envoy listener filter chains

README.md
=> docs(*): update docs per new release

README.md
=> update readme for non-default namespaces
