openservicemesh/osm-health

- pkg/osm/smi.go
- pkg/osm/types.go
This PR adds a mapping from OSM Controller version to supported TrafficTarget, TrafficSplit, HTTPRouteGrup versions.
The PR is stacked on https://github.com/openservicemesh/osm-health/pull/13
---
A script that is helpful to extract the SMI versions:
```bash
for x in $(seq 5 9); do git checkout "upstream/release-v0.${x}"; echo "\n----\nv0.$x"; grep -Iir 'github.com/servicemeshinterface/smi-sdk-go/pkg/apis' $(find . -type f -name '*.go' | grep -v _test.go) | awk -F: '{print $2}' | sort | uniq; done; git checkout main
```
> Adding a mapping from OSM Controller version to supported SMI TrafficTarget, TrafficSplit, HTTPRouteGrup versions

- pkg/common/printer.go
check(*): Include error string when printing check outcomes
> check(*): Include error string when printing check outcomes

- pkg/envoy/lds.go
This change defines the listener types to make the logs clearer about
which listener is missing between two Pods.
> fix(lds): define listener types

- pkg/connectivity/pod-to-pod.go
- pkg/envoy/eds.go
- pkg/envoy/errors.go
This PR adds a check - whether the source Envoy has at least one of the Destination endpoints.
Signed-off-by: Delyan Raychev <delyan.raychev@microsoft.com>
> Check whether source Envoy is configured with at least one destination endpoint

- pkg/common/types.go
- pkg/envoy/eds.go
- pkg/envoy/envoy_container_logs.go
- pkg/envoy/lds.go
- pkg/kubernetes/namespace/injected.go
- pkg/kubernetes/namespace/monitored.go
- pkg/kubernetes/pod/containers.go
- pkg/kubernetes/pod/events.go
- pkg/kubernetes/pod/labels.go
This PR adds 2 new functions to the `Runnable` interface:
- `Suggestion()` - returns a string with a suggestion on how to fix an error that may have been discovered (or an empty string if no error is discovered)
- `FixIt()` - actually applies the fix suggested by the previous function
Signed-off-by: Delyan Raychev <delyan.raychev@microsoft.com>
> Adding Suggestion() and FixIt() to common.Runnable interface

- pkg/envoy/eds.go
This change makes the EDS check for a specific Pod IP in the endpoints
of the source Envoy config check all of the endpoints, not just the
first.
> fix(envoy): check all endpoint configs for Pod IP

- go.mod
- go.sum
- pkg/kubernetes/pod/labels.go
Use the proxy label check in `openservicemesh/osm/pkg/mesh`.
This is a follow up to https://github.com/openservicemesh/osm/pull/3899
> chore(pkg/kubernetes): Use osm mesh pkg for proxy label check

- pkg/common/printer.go
Yay for colors! Follow up PR coming soon for formatting outcomes in a table
Before:
After:
> format(printer): add colors to test outcomes

- pkg/envoy/parse.go
- tests/sample-enovy-config-dump-bookstore.json
This change imports the HTTP health check filter package for parsing the
Envoy config to succeed when Envoy active health checks are enabled.
> fix(envoy): add HTTP health check filter import for parse

- go.sum
- pkg/connectivity/pod-to-pod.go
- pkg/envoy/cds.go
- pkg/envoy/cds_test.go
This change adds a new check in the pod-to-pod connectivity checks that
verifies the source Envoy config contains a cluster with a name matching
one of the Kubernetes services the destination pod is backing.
> feat(connectivity): add CDS cluster name check

- cmd/connectivity.go
- cmd/connectivity_pod_to_url.go
- pkg/connectivity/pod-to-url.go
- tests/pod-to-url.sh
This PR adds a wireframe for a new check from a given POD to an URL.
Example:
```bash
./bin/osm-health connectivity pod-to-url \
"bookbuyer/bookbuyer-8858fb5f6-cvlxz" \
"http://bookstore.bookstore/"
```
---
Run this with:
```bash
rm -rf ./bin/osm-health && make && ./tests/pod-to-url.sh
```
Signed-off-by: Delyan Raychev <delyan.raychev@microsoft.com>
> Adding the wireframe of a new POD to URL check

- pkg/envoy/lds.go
- pkg/envoy/lds_test.go
This change fixes the listener checks for pod-to-pod connectivity to
look in all of the listeners, not just the first.
> fix(connectivity): check all LDS listeners

- pkg/connectivity/pod-to-pod.go
- pkg/kubernetes/namespace/errors.go
- pkg/kubernetes/namespace/monitored.go
May be unnecessary, does similar work to the isMonitoredBy check. Would make sense to move into pkg/kubernetes/namespace
> check(monitored): are namespaces in the same mesh

- pkg/connectivity/pod-to-pod.go
- pkg/envoy/envoy_container_logs.go
- pkg/kubernetes/podhelper/container_logs.go
- pkg/kubernetes/podhelper/containers.go
- pkg/kubernetes/podhelper/containers_test.go
- pkg/kubernetes/podhelper/errors.go
- pkg/kubernetes/podhelper/events.go
- pkg/kubernetes/podhelper/labels.go
- pkg/kubernetes/podhelper/labels_test.go
- pkg/kubernetes/podhelper/types.go
- pkg/osm/osm_controller_logs.go
- pkg/osm/status.go
> check(osm): Check for bad logs in osm controller pods

- pkg/kuberneteshelper/pod.go
This change utilizes helpers in the `clientcmd` package to load the
Kubernetes config to avoid dealing with the `$KUBECONFIG` environment
variable directly. The specific issue I ran into with the current
implementation was when multiple files are defined in `$KUBECONFIG`:
https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#the-kubeconfig-environment-variable
> fix(k8s): use standard rules for loading k8s config

- pkg/connectivity/pod-to-pod.go
- pkg/connectivity/pod-to-url.go
- pkg/envoy/config.go
- pkg/envoy/eds.go
- pkg/envoy/envoy_container_logs.go
- pkg/ingress/pod.go
- pkg/kubernetes/namespace/annotations.go
- pkg/kubernetes/namespace/labels.go
- pkg/kubernetes/podhelper/container_logs.go
- pkg/kubernetes/podhelper/containers.go
- pkg/kubernetes/podhelper/events.go
- pkg/kubernetes/podhelper/labels.go
- pkg/kuberneteshelper/pod.go
This resolves inconsistent imports of corev1 and metav1 imports.
From this point onwards, imports for both packages should
always be "corev1" and "metav1" by convention in this repo.
> chore(*): refactor corev1 and metav1 imports

- go.mod
- go.sum
- pkg/connectivity/pod-to-pod.go
- pkg/smi/access/routes_validity.go
- pkg/smi/access/traffic_target.go
- pkg/smi/access/types.go
- pkg/smi/access/v1alpha2/methods.go
- pkg/smi/access/v1alpha3/methods.go
- pkg/smi/constants.go
- diagnostic check for existence of traffic targets
- pass/fail check for route validity - ideally this check should only be carried out if the previous one passes but for now we don't have the right logic for that (ref #73)
- added packages to be able to version smi access client based on osm controller version
> smi(checks): add checks for traffic target and valid route

- pkg/kubernetes/podhelper/events.go
Currently, the check for Kubernetes events lists all events in the
namespace. This change filters out all events except those for the
specified pod.
> fix(events): limit to one pod

- pkg/connectivity/pod-to-pod.go
- pkg/kubernetes/podhelper/endpoints.go
- pkg/kubernetes/podhelper/endpoints_test.go
- pkg/kubernetes/podhelper/errors.go
This change adds a new pod-to-pod connectivity check to verify the
destination pod is referenced in a Kubernetes Endpoints resource.
> feat(connectivity): check destination pod is in an Endpoint

- pkg/connectivity/pod-to-pod.go
- pkg/envoy/sds.go
- pkg/envoy/sds_test.go
Adds a check to the pop-to-pod connectivity check to verify the
presence of service certificates for the src and dst, the outbound
mTLS root certificate in the src's envoy config, and the inbound
mTLS root certificate in the dst's envoy config.
Signed-off-by: jaellio <jaellio@microsoft.com>
> feat(envoy/sds): check envoy certificates

- pkg/common/outcomes/pass.go
- pkg/connectivity/pod-to-pod.go
- pkg/kubernetes/podhelper/errors.go
- pkg/kubernetes/podhelper/service.go
We want to make sure that there is at least one service associated with the destination pod.
> Adds service check and Msg field to PassOutcome

- pkg/connectivity/pod-to-pod.go
- pkg/osm/utils.go
- pkg/osm/utils_test.go
Removes the hard-coded OSM version and mesh name in the pod-to-pod connectivity check. The OSM version and mesh name are obtained from the label values in the OSM controller deployment using the given controller namespace.
As an alternative to this solution the `/version` endpoint on the `osm-controller` pod could be queried to obtain the OSM version and mesh name.
> feat(osm): dynamically get osm version and mesh name

- pkg/osm/utils.go
Fixes bug. Mesh name was being set using the name label rather than the instance label's value.
> fix(osm): mesh name set with instance label

- pkg/osm/smi.go
- pkg/osm/types.go
- pkg/osm/types_test.go
- pkg/smi/access/errors.go
- pkg/smi/access/routes.go
- pkg/smi/access/routes_existence.go
- pkg/smi/access/routes_test.go
- pkg/smi/access/routes_validity.go
chore(smi): Refactor route kind support check
Refactors TrafficTarget route kind support check
to check for the supported route kinds per osm version.
> chore(smi): Refactor route kind support check

- pkg/envoy/cds.go
- pkg/envoy/config.go
- pkg/envoy/lds.go
- pkg/envoy/rds.go
- pkg/osm/utils/utils.go
- pkg/osm/utils/utils_test.go
- pkg/osm/version/annotations.go
- pkg/osm/version/envoy.go
- pkg/osm/version/ingress.go
- pkg/osm/version/listener_names_per_osm_version.go
- pkg/osm/version/smi.go
- pkg/osm/version/types_test.go
* Check for Envoy cluster name prefix in pod-to-pod cds check.
For osm v0.10 onwards, the Envoy cluster name in the cds check
may have the port number appended to the cluster name.
* Add EnvoyAdminPort information for osm v0.10 & v0.11.
* Check for Envoy listener name prefix in pod-to-pod filter chains check.
For osm v0.10 onwards, the Envoy filter chains have the port number
and traffic type appended. When checking for possible filter chain
names, check for the prefix instead (without the port num & traffic type).
* Check for Envoy route domain service name prefix in pod-to-pod
rds check. For osm v0.10 onwards, rds dynamic_route_config names
have the port number appended.
* Add info for osm v0.10 and v0.11 in pkg/osm/version checks and utils.
* Ensure release version format util always …
> feat(*): support osm-health for osm v0.10 & v0.11

- pkg/kubernetes/podhelper/endpoints.go
- pkg/kubernetes/podhelper/endpoints_test.go
If there is an endpoint in a namespace that includes a tested pod (e.g. `osm-health connectivity pod-to-pod default/pod1 default/pod2`) that has an address with no targetRef then it panics with a segmentation violation:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1ab749e]
goroutine 1 [running]:
github.com/openservicemesh/osm-health/pkg/kubernetes/podhelper.EndpointsCheck.Run(0x2691d48, 0xc000ded8c0, 0xc000614c00, 0xc000d83500, 0xd)
/home/trstringer/dev/osm-health/pkg/kubernetes/podhelper/endpoints.go:45 +0x15e
github.com/openservicemesh/osm-health/pkg/runner.Run(0xc00062ba90, 0x27, 0x27, 0xc000440000, 0xc000614400, 0x235dd80)
/home/trstringer/dev/osm-health/pkg/runner/runner.go:12 +0xb1 …
```
> Fix panic when there is an endpoint address with no targetRef

- pkg/envoy/parse.go
This PR fixes the following error:
```
ERR Error parsing JSON bytes error="proto:\u00a0(line 1627:21): unable to resolve \"type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy\": \"not found\"" file=parse.go:29 module=envoy
```
> Add tcp_proxy for envoy config

- cmd/connectivity_pod_to_pod.go
- cmd/connectivity_pod_to_url.go
- cmd/control_plane_status.go
- cmd/ingress_to_pod.go
- pkg/ingress/pod.go
- pkg/kubernetes/namespace/monitored.go
* Adds missing command examples
* Updates all command examples to follow a consistent format
* Uses mesh-name detection from env for ingress checks (this was previously hardcoded as "osm")
> remove todos
